
[functions.rozpocznij-zlecenie]
enabled = true
verify_jwt = true
import_map = "./functions/rozpocznij-zlecenie/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/rozpocznij-zlecenie/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/rozpocznij-zlecenie/*.html" ]

[functions.odbierz-nagrode]
enabled = true
verify_jwt = true
import_map = "./functions/odbierz-nagrode/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/odbierz-nagrode/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/odbierz-nagrode/*.html" ]
